development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  url:  postgres://qumbtaxmqseqau:49d51e57efc48af135c4aa155e32f87bbf49472a28aadc664a3e2716d33317f3@ec2-50-16-241-91.compute-1.amazonaws.com:5432/d45feklkth7fcd
  channel_prefix: veryhappyapp_production
